vim.keymap.set('n', '<leader>wv', '<C-w>v', {desc = "vertical split"})
vim.keymap.set('n', '<leader>ws', '<C-w>s', {desc = "split"})
vim.keymap.set('n', '<leader>wq', '<C-w>q', {desc = "quit window"})
vim.keymap.set('n', '<leader>wh', '<C-w>h', {desc = "go left"})
vim.keymap.set('n', '<leader>wj', '<C-w>j', {desc = "go down"})
vim.keymap.set('n', '<leader>wk', '<C-w>k', {desc = "go up"})
vim.keymap.set('n', '<leader>wl', '<C-w>l', {desc = "go right"})
vim.keymap.set('n', '<leader>ww', '<C-w>w', {desc = "switch window"})
